# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.10.0

pipelines:
  default:
    - step:
        script:
          -mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=khoandirox -Dsonar.login=$SONAR_TOKEN
    - step:
        caches:
          - node
        name: Deployment
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run deploy
